package com.github.newswhip.linkstore.service.reports;

import java.util.Collection;

/**
 * Generates a report that can be easily printed or written
 *
 * @param <T>
 */
public abstract class ReportGenerator<T> {

    public Collection<String> getReport() {
        return this.format(getData());
    }

    /**
     * Abstract method to format any report generated by the getData method into a Collection of String.
     *
     * @param raw
     * @return
     */
    protected abstract Collection<String> format(T raw);

    /**
     * Can return any type of report.
     * Reports will be converted by the format method into a collection of strings.
     *
     * @return
     */
    protected abstract T getData();
}
